### ISSUE TITLE
Add bind address option to  .env docker-compose

### ISSUE THREAD

**Issue by isl3** [vivo-project/VIVO#3939]
As far as I can tell the docker compose will always bind to 0.0.0.0:8983 and 0.0.0.0:8080 respectfully, this causes me trouble as I am trying to run vivo behind a reverse proxy and not expose solr to the entire network.

Please the option to configure what address the containers or the network binds to on the host system.

My current work around is to edit the docker compose before running `docker compose up -d` as follows.
```
  solr:
    image: vivoweb/vivo-solr:latest
    environment:
      - RESET_CORE=${RESET_CORE}
      - VERBOSE=${VERBOSE}
    ports:
      - "127.0.0.1:8983:8983"
    networks:
      - vivo

  tomcat:
   .....
    ports:
      - "127.0.0.1:8080:8080"
```
